### ISSUE TITLE
Loading API Key

### ISSUE THREAD

**Issue by amadeobrands** [bunq/tinker_php#21]
Instaled Tinker but get the  following errors?
Not sure why or what todo?
I run from Ubuntu?

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bunq/sdk_php 0.13.2 -> satisfiable by bunq/sdk_php[0.13.2].
    - bunq/sdk_php 0.13.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-curl.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
`

**Comment by amadeobrands** [comment]
Also when I run sudo ... get the following error?

`hw01@hw01-VirtualBox:~/Bunq_API01$ sudo bash <(curl -s https://tinker.bunq.com/php/setup.sh)
bash: /dev/fd/63: No such file or directory
`

**Comment by OGKevin** [comment]
well, the error message states that you are missing `ext-mbstring` 

> - bunq/sdk_php 0.13.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.

so i would suggest you to install this and then try again.

**Comment by amadeobrands** [comment]
Ok thank you will do that :)
