### ISSUE TITLE
How to get a wildcard API for Sandbox Env

### ISSUE THREAD

**Issue by sankarcn** [bunq/tinker_php#27]
Hello,
This is more of a question rather than an issue.  I am looking to get an API Key in BUNQ sandbox env which is wildcard API Key, so that I can create an Installation Context and proceed to use the API's. 
I was doing a POST to  https://public-api.sandbox.bunq.com/v1/sandbox-user, but this key gives me an error when trying to create an API context. 
Thanks in Advance.

**Comment by OGKevin** [comment]
If you want a wildcard IP, you must enable this via the sandbox bunq app, the same way you would do on production. 

Think about it, it would be a security risk to be able to enable this via the API itself.
